# Generated by Django 4.2.3 on 2023-08-15 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='Sellers',
            new_name='Seller',
        ),
        migrations.RenameModel(
            old_name='Transacts',
            new_name='Transact',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.AlterField(
            model_name='transact',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.product'),
        ),
    ]
