# Generated by Django 4.2.3 on 2023-08-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_product_rename_sellers_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transact',
            name='comisionChecker',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transact',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
