# Generated by Django 4.2.3 on 2023-08-15 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='url',
            new_name='token',
        ),
    ]
