# Generated by Django 4.2.3 on 2023-08-15 20:17

import API.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='access_tokn',
            field=models.CharField(default=API.models.Seller.generate_access_tokn, max_length=50),
        ),
    ]
