# Generated by Django 4.2.3 on 2023-08-15 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_seller_access_tokn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transact',
            name='comisionChecker',
        ),
    ]
